# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KhmuMdQV-8eRT7KFrqsC2I0DjZLfrg2g
"""

import numpy as np
import pandas as pd
import spacy
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.metrics import accuracy_score 
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
import spacy
nlp = spacy.load("en_core_web_sm")
import string
punct=string.punctuation
from spacy.lang.en.stop_words import STOP_WORDS
stopwords = list(STOP_WORDS)
import pickle

!pip install flask-ngrok

!pip install flask

from flask import Flask, jsonify, request
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)


@app.route("/", methods=["POST"])
def home():
  data = request.json
  review = data['review']
  review = review.replace('<br />', ' ')
  review = review.replace('\d+', '')
  review = review.lower()
  score=pipe.predict(([review]))[0]
  return score

pipe=pickle.load(open('/content/drive/MyDrive/modelfortestcentre.pkl','rb'))

app.run()

